name: Update README with stars information

on:
  watch:
    types: [started]

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get stargazers
        id: get_stargazers
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: 'get_stargazers'
      - name: Build stars list
        id: build_stars_list
        run: |
          echo "🌟 **Thanks to our ${{ steps.get_stargazers.outputs.stargazers }} stargazers!** 🌟" > README.md
          echo "" >> README.md
          curl -s https://api.github.com/repos/${{ github.repository }}/stargazers | jq -r '.[].login' | sort | uniq | while read login; do echo "- @$login"; done >> README.md
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Update README with latest stargazers"
          add: README.md
